routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', function () {
    return view('order');
});

Route::resource('/order','OrderController');

Auth::routes();

Route::get('login/google', 'Auth\LoginController@redirectToGoogle')->name('login.google');
Route::get('login/google/callback', 'Auth\LoginController@handleGoogleCallback');

Route::group(['middleware'=>['auth']], function(){  
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('/admin','Admin\AdminOrderController');
	Route::get('apiorder', 'Admin\AdminOrderController@apiOrder')->name('api.order');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guarded = ['id'];
    protected $table = 'orders';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/AdminOrderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;
use App\Order;
use Illuminate\Support\Facades\Auth; //untukmenggunakan Controller Auth
use Illuminate\Support\Facades\DB;

class AdminOrderController extends Controller
{
    
    public function index()
    {
        return view('dashboard.order');
    }

    
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);
        return view('dashboard.detail', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order::find($id);
        return view('dashboard.editOrder', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $order = Order::find($id);
        $order->update([
            'name' => request('name'),
            'email' => request('email'),
            'hp' => request('hp'),
            'fb' => request('fb'),
            'address' => request('address'),
            'message' => request('message'),
            'queue' => request('queue'),
            'hope' => request('hope'),
            'status' => request('status'),
        ]);

        return redirect()->back()->with('success','Berhasil di ubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $orders = Order::find($id);
        $orders->delete();
    }

    public function apiOrder(Request $request){

        DB::statement(DB::raw('set @rownum=0'));
        $orders = Order::select([
            DB::raw('@rownum := @rownum + 1 AS no'),
            'id',
            'name',
            'email',
            'hp',
            'fb',
            'address',
            'message',
            'ref',
            'queue',
            'hope',
            'status',
            'info',
        ])->latest('id');

        $datatables = Datatables::of($orders);

        if($keyword = $request->get('search')['value']){
            $datatables->filterColumn('no', 'whereRaw', '@rownum + 1 like ?', ["{$keyword}%"]);
        }

        return $datatables->addColumn('action', function($orders){
            return '<a onclick="showOrder('.$orders->id.')" class="btn btn-outline btn-primary btn-xs" style="margin-right:2px">Detail</a>'.
                    '<a onclick="editOrder('.$orders->id.')" class="btn btn-outline btn-success btn-xs" style="margin-right:2px">Edit</a>'.
                    '<a onclick="deleteOrder('.$orders->id.')" class="btn btn-outline btn-danger btn-xs" style="margin-right:2px">Delete</a>';

        })->make(true);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class OrderController extends Controller
{
    public function create()
    {
        return view('order');
    }
    public function store(Request $request)
    {
        // Order::create([
        //     'name'    => request('name'),
        //     'email'   => request('email'),
        //     'hp'      => request('hp'),
        //     'fb'      => request('fb'),
        //     'address' => request('address'),
        //     'message' => request('message'),
        //     'ref'     => request('ref'),
        //     'queue'   => request('queue'),
        //     'hope'    => request('hope'),

        // ]);

        $order = new Order;//DB::table('orders');

        $order->name = $request->name;
        $order->email = $request->email;
        $order->hp = $request->hp;
        $order->fb = $request->fb;
        $order->address = $request->address;
        $order->message = $request->message;
        $order->queue = $request->queue;
        $order->hope = $request->hope;

        if ($request->hasFile('ref')) {
            $file = $request->file('ref'); 
            $filename = $request->name.$file->getClientOriginalName();
            // Storage::disk('uploads')->put('file', $file);
        // dd(store('docs',$filename));

            // $request->file('ref')->storeAs('docs',$filename);
            $file->move('uploads/file/', $filename);
            $order->ref = $filename; 
        }

        $order->save();

        return redirect()->back()->with('success', 'Order anda sudah kami terima');;
    }
}

resources/views/dashboard/detail.blade.php
@extends('dashboard.masterDashboard')
@section('title')
Orderan Detail
@endsection
@section('content')
	<div id="page-wrapper">
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Orderan</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-info">
					<div class="panel-heading">
						<h3 class="panel-title">Orderan Detail</h3>
					</div>
					<div class="panel-body">
						<div class="row">
                <div class=" col-md-12 col-lg-12 "> 
                 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td><b>Nama</b></td>
                        <td>{{$order->name}}</td>
                      </tr>
                      <tr>
                        <td><b>Email</b></td>
                        <td>{{$order->email}}</td>
                      </tr>
                      <tr>
                        <td><b>Nomor Hp/WA</b></td>
                        <td>{{$order->hp}}</td>
                      </tr>
                      <tr>
                        <td><b>Facebook</b></td>
                        <td>{{$order->hp}}</td>
                      </tr>
                      <tr>
                        <td><b>Alamat</b></td>
                        <td>{{$order->address}}</td>
                      </tr>
                      <tr>
                        <td><b>Pesan / Keperluan</b></td>
                        <td>{{$order->message}}</td>
                      </tr>
                      <tr>
                        <td><b>Reffrensi</b></td>
                        <td><a href="{{asset('uploads/file/'.$order->ref) }}">Download</a></td>
                      </tr>
                      <tr>
                        <td><b>Siap Mengantri</b></td>
                        <td>{{$order->queue}}</td>
                      </tr>
                      <tr>
                        <td><b>Harapan selesai</b></td>
                        <td>{{$order->hope}}</td>
                      </tr>
                      <tr>
                        <td><b>Status</b></td>
                        <td>{{$order->status}}</td>
                      </tr>
                    </tbody>
                    <tr>
                      <td><a class="btn btn-info" href="{{route('admin.edit',$order->id)}}">Edit</a></td>
                      <td></td>
                      
                    </tr>
                  </table>
                </div>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>
@endsection

resources/views/dashboard/editOrder.blade.php
@extends('dashboard.masterDashboard')
@section('title')
Edit Orderan
@endsection
@section('content')
	<div id="page-wrapper">
		<div class="row">
			<div class="col-lg-12">
				@include('layouts.patrials._alerts')
				<h1 class="page-header"> Edit Orderan</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-info">
					<div class="panel-heading">
						<h3 class="panel-title">Edit</h3>
					</div>
					<div class="panel-body">
						<div class="row">
							<form action="{{route('admin.update', $order->id)}}" method="post" role="form" enctype="multipart/form-data">
                    {{csrf_field()}}
                    {{ method_field('PATCH') }}
                <div class=" col-md-12 col-lg-12 "> 
                 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td><b>Nama</b></td>
                        <td><input placeholder="Ridwan" class="form-control" type="" name="name" value="{{$order->name}}"></td>
                      </tr>
                      <tr>
                        <td><b>Email</b></td>
                        <td><input readonly class="form-control" type="email" name="email" value="{{$order->email}}"></td>
                      </tr>
                      <tr>
                        <td><b>Nomor Hp/WA</b></td>
                        <td><input class="form-control"" name="hp" value="{{$order->hp}}"></td>
                      </tr>
                      <tr>
                        <td><b>Facebook</b></td>
                        <td><input class="form-control" type="link" name="fb" value="{{$order->hp}}"></td>
                      </tr>
                      <tr>
                        <td><b>Alamat</b></td>
                        <td><textarea placeholder="Contoh : jl.pesangrahan" class="form-control" type="text" name="address">{{$order->address}}</textarea></td>
                      </tr>
                      <tr>
                        <td><b>Pesan / Keperluan</b></td>
                        <td><textarea class="form-control" type="text" name="message">{{$order->message}}</textarea></td>
                      </tr>
                      <tr>
                        <td><b>Status</b></td>
                        <td>
                          <select name="status" class="form-control">
                            <option {{$order->status=='Waiting' ? 'selected' : ''}} value="Waiting">Waiting</option>
                            <option {{$order->status=='Pending' ? 'selected' : ''}} value="Pending">Pending</option>
                            <option {{$order->status=='Completed' ? 'selected' : ''}} value="Completed">Completed</option>
                            
                            <option {{$order->status=='In Proses' ? 'selected' : ''}} value="In Proses">In Proses</option>
                          </select>
                        </td>
                      </tr>
                      <tr>
                        <td><b>Reffrensi</b></td>
                        <td><a href="{{$order->ref}}">Download</a></td>
                      </tr>
                      <tr>
                        <td><b>Siap Mengantri</b></td>
                        <td>
                        	<select name="queue" id="queue">
                        		<option value="Ya" {{$order->queue=="YA"?'selected':''}}>Ya</option>
                        		<option value="Tidak" {{$order->queue=="Tidak"?'selected':''}}>Tidak</option>
                        	</select>
                        </td>
                      </tr>
                      <tr>
                        <td><b>Harapan selesai</b></td>
                        <td><input id="datepicker" class="form-control" type="" name="hope" value="{{$order->hope}}"></td>
                      </tr>
                      <tr>
                        <td></td>
                        <td><input class="btn btn-primary" type="submit" name="submit"></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                </form>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	</div>
@endsection

resources/views/dashboard/order.blade.php
@extends('dashboard.masterDashboard')
@section('title')
Orderan
@endsection
@section('content')
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Semua Orderan</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Semua Orderan
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" id="order-table">
                        <thead>
                            <tr>
                                {{-- <th>No</th> --}}
                                <th >Nama</th>
                                <th >Pesan</th>
                                <th>Status</th>
                                <th>Dead line</th>
                                <th width="110">Action</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
@endsection
@section('js')
<script type="text/javascript">
	var table = $('#order-table').DataTable({
		order: [[0,'desc']],
		processing: true,
		serverSide: true,
		ajax: "{{route('api.order')}}",
		columns:[
			// {data: 'no', name: 'no'},
			{data: 'name', name: 'name'},
			{data: 'message', name: 'message'},
			{data: 'status', name: 'status'},
      {data: 'hope', name: 'hope'},
			{data: 'action', name: 'action', ordertable: false, searchable:false}
		]
	})

	/*Delete Data*/
      function deleteOrder(id){
        var csrf_token = $('meta[name="csrf-token"]').attr('content');

        swal({
          title: 'Kamu yakin ?',
          text: "Data Order yang di hapus tidak akan kembali!",
          type: 'warning',
          showCancelButton: true,
          cancelButtonColor: '#d33',
          confirmButtonColor: '#3085d6',
          confirmButtonText: 'Ya, Hapus ini!'
        }).then(function(){
          $.ajax({
            url: "{{ url('admin') }}" + '/' + id,
            type: "DELETE",
            data: {'_mehtod' : 'DELETE', '_token' : csrf_token},
            success: function(data){
              table.ajax.reload();
              swal({
                title:'Berhasil',
                text: 'Orderan Sudah di hapus',
                type: 'success',
                timer: '1500'
              })
            },
            error: function(){
              swal({
                title: 'Oops',
                text: 'Something went wrong',
                type: 'error',
                timer: '1500'
              })
            }
          })
        })
      }

     function editOrder(id){
     	var url =  "{{ url('admin') }}"+"/"+id+"/edit";
     	window.location = url;
     }

     function showOrder(id){
     	window.location = "{{url('admin')}}"+"/"+id;
     }
</script>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/patrials/_alerts.blade.php
@if (session('success'))
	<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<i class="material-icons">close</i>
		</button>
		<span style="text-align: center;">
			<b>{{ session('success') }}</b></span>
	</div>
@endif

@if (session('info'))
  	<div class="alert alert-info">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<i class="material-icons">close</i>
		</button>
		<span style="text-align: center;">
			<b>{{ session('info') }}</b></span>
	</div>
@endif

@if (session('danger'))
  <div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<i class="material-icons">close</i>
		</button>
		<span style="text-align: center;">
			<b>{{ session('danger') }}</b></span>
	</div>
@endif

resources/views/order.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Order Desain</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    {{-- <script src="//code.jquery.com/jquery-2.1.3.min.js"></script> --}}
    <!------ Include the above in your HEAD tag ---------->
    <link rel="stylesheet" type="text/css" href="{{asset('css/order.css')}}">
    {{-- <script src="{{asset('js/order.js')}}"></script> --}}
    <script src="{{asset('js/date.js')}}"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {{-- CSS DASHBOARD --}}
    
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{{asset('assets/css/material-dashboard.css?v=2.0.0')}}">
    <!-- Documentation extras -->
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{{asset('assets/assets-for-demo/demo.css" rel="stylesheet')}}" />
    <!-- iframe removal -->
</head>
<body>
    <br>
    <div>@include('layouts.patrials._alerts')</div>
    <br>
    <div class="container" id="order-form">
        
            <form action="{{route('order.store')}}" class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
                {{csrf_field()}}
                <h2>Order Desain</h2>
                <div class="form-group">
                    <label for="name" class="col-sm-3 control-label">Nama Lengkap</label>
                    <div class="col-sm-9">
                        <input required  type="text" id="name" name="name" placeholder="Nama" class="form-control" autofocus>
                        <span  class="errorval errorRegis" id="errorName"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-sm-3 control-label">Email</label>
                    <div class="col-sm-9">
                        <input required  type="email" name="email" id="email" placeholder="example@sample.com" class="form-control" autofocus>
                        <span  class="errorval errorRegis" id="errorEmail"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="phoneNumber" class="col-sm-3 control-label">Nomor Hp/WA </label>
                    <div class="col-sm-9">
                        <input required type="number" id="hp" placeholder="Phone number" name="hp" class="form-control">
                        <span  class="errorval errorRegis" id="errorHp"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="fb" class="col-sm-3 control-label">Facebook</label>
                    <div class="col-sm-9">
                        <input type="link" id="fb" placeholder="Facebook" name="fb" class="form-control">
                        <span  class="errorval errorRegis" id="errorFb"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="address" class="col-sm-3 control-label">Alamat Lengkap</label>
                    <div class="col-sm-9">
                        <textarea required class="form-control" name="address" id="address"></textarea>
                        <span  class="errorval errorRegis" id="errorAddress"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="message" class="col-sm-3 control-label">Pesan / Keperluan</label>
                    <div class="col-sm-9">
                        <textarea rows="20" required class="form-control" name="message" id="message" placeholder="Contoh order untuk loker
                        Info Lowongan Kerja

Pondok IT adalah sebuah suatu tempat pendidikan IT yang berada di Yogyakarta yang selain membekali santrinya dengan pengetahuan Teknologi Informasi dan Komputer (TIK), juga membekali mereka dengan ilmu agama. 

Dibutuhkan 2 Staf Manajemen di Pondok IT

📝 Kriteria
1. Muslim Taat
2. Menyukai dunia IT /Lingkungan pondok
3. Jujur, Disiplin, Bertanggung Jawab
4. Min Lulusan SMK/SMA/MA
5. Tidak Merokok
6. Diutamakan Belum Nikah
7. Usia Max 27 Tahun
8. Semangat Dalam Belajar / Mau Mengembangkan Kemampuan
9. Bersedia dibimbing dan diarahkan

🎁 Fasilitas
1. Gaji Pokok
2. Makan 3 kali sehari. 
3. Tempat Tinggal
4. Free Wifi di lingkungan pondok. 
5. Kajian Islam
6. Pinjaman Laptop

🗂 Berkas Lamaran
1. Surat lamaran pekerjaan. 
2. Daftar Riwayat Hidup (CV). 
3. Fotocopy ijazah terakhir.
4. Sertifikat lain yg mendukung. 
5. Fotocopy KTP.
6. Foto berwarna 4x6

Berkas lamaran dikirimkan dalam format PDF ke WA 

ℹ Informasi
Hubungi Rulli (Wa/Telepon) : 085228802828 

📭 *Alamat Pondok Programmer(Pondok IT), Glagah lor, No 64 RT 02, Desa tamanan, kecamatan banguntapan, Bantul, Yogyakarta 55191 www.PondokIT.com
www.pondokprogrammer.com"></textarea>
                        <span  class="errorval errorRegis" id="errorMessage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="ref" class="col-sm-3 control-label">Refrensi</label>
                    <div class="col-sm-9">
                        <input style="height: 40px;" type="file" name="ref" id="ref" class="form-control">
                        <span  class="errorval errorRegis" id="errorRef"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="queue" class="col-sm-3 control-label">Siap Mengantri</label>
                    <div class="col-sm-9">
                        <select style="height: 35px;" class="form-control" id="queue" name="queue">
                            <option value="Ya" class="form-control">Ya</option>
                            <option value="Tidak" class="form-control">Tidak</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="hope" class="col-sm-3 control-label">Harapan Selesai</label>
                    <div class="col-sm-9">
                        <input required type="date" id="datepicker" name="hope" class="form-control">
                        <span  class="errorval errorRegis" id="errorHope"></span>
                    </div>
                </div>
                 <!-- /.form-group -->
                <button id="submit" type="submit" class="btn btn-primary btn-block">Kirim</button>
            </form> <!-- /form -->
        </div> <!-- ./container -->
</body>
<script src="{{asset('js/order.js')}}"></script>

</html>